services:
  yt-dlp-web:
    build: .
    container_name: downloader
    ports:
      - 80:3000
    volumes:
      - ${DOWNLOAD_PATH:-/mnt/downloads}:/downloads
      - ./data:/data
    env_file: .env
    environment:
      - DOWNLOAD_PATH=/downloads
    restart: unless-stopped
